### PR TITLE
bump bom to 1500.ve4d05cd32975

### PR DESCRIPTION
**Pull request by jetersen**
trying to unblock https://github.com/jenkinsci/bom/pull/1275

Seems dependabot is configured but not running on the repo. Most likely need to reach out to GitHub support.

### CODE REVIEW

**Review by jglick — APPROVED** [review]

**Comment by jetersen** [comment]
Forgot to test with incremental, potentially could still have issues 😅

**Comment by jetersen** [comment]
not PCT ready, let me submit PR 😅

**Comment by jetersen** [comment]
Or I should not delete my branch 🗡️

**Comment by jetersen** [comment]
All good, still getting cyclic dependency but the test are not blocked by the current cyclic dependency issue.

Seems it depends what tests written and what plugins they depend on.

**Comment by jglick** [comment]
https://github.com/jenkinsci/pipeline-groovy-lib-plugin/releases/tag/598.vcd66b_a_336510

**Pull request merged**
